# -*- coding: utf-8 -*-
"""Resume parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IqBxvFOy53GNpI6EoQO7f-TFy3XYGefB
"""

!pip install pymupdf spacy
!python -m spacy download en_core_web_sm

import fitz  # PyMuPDF
import re
import spacy
from spacy.matcher import PhraseMatcher
import json

# Load SpaCy's small English model
nlp = spacy.load("en_core_web_sm")

# ----------------------------------------------------
# 1. TEXT EXTRACTION
# ----------------------------------------------------
def extract_text_from_pdf(pdf_path):
    """Extracts raw text from a PDF file using PyMuPDF."""
    doc = fitz.open(pdf_path)
    text = ""
    for page in doc:
        text += page.get_text()
    return text

# ----------------------------------------------------
# 2. REGEX EXTRACTION (Emails & Phone Numbers)
# ----------------------------------------------------
def extract_contact_info(text):
    """Uses Regex to find standard contact information patterns."""
    # Standard email regex
    email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
    emails = re.findall(email_pattern, text)

    # Robust phone pattern targeting formats like 202-555-0120
    phone_pattern = r'\b(?:\+?\d{1,3}[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b'
    phones = re.findall(phone_pattern, text)

    return {
        "email": emails[0] if emails else None,
        "phone": phones[0] if phones else None
    }

# ----------------------------------------------------
# 3. SPA-CY NLP EXTRACTION (Name & Skills)
# ----------------------------------------------------
def extract_name(text):
    """Extracts the person's name using SpaCy NER (PERSON tag)."""
    doc = nlp(text)
    for ent in doc.ents:
        # Grabs the first 2+ word name found (e.g., 'Rachel Nathan')
        if ent.label_ == "PERSON" and len(ent.text.split()) >= 2:
            return ent.text.strip()
    return None

def extract_skills(text, skill_db):
    """Extracts predefined skills using SpaCy's PhraseMatcher."""
    doc = nlp(text.lower()) # Lowercase for case-insensitive matching
    matcher = PhraseMatcher(nlp.vocab, attr="LOWER")

    # Create patterns for the skills database
    patterns = [nlp.make_doc(skill) for skill in skill_db]
    matcher.add("SKILLS", patterns)

    matches = matcher(doc)
    skills_found = set()

    for match_id, start, end in matches:
        span = doc[start:end]
        skills_found.add(span.text.upper() if len(span.text) <= 3 else span.text.title())

    return list(skills_found)

# ----------------------------------------------------
# 4. EXPERIENCE EXTRACTION (Heuristic Segmentation)
# ----------------------------------------------------
def extract_experience(text):
    """Extracts text segments belonging to the Experience section."""
    lines = text.split('\n')
    experience_text = []
    inside_experience = False

    trigger_words = ["experience", "work history", "employment", "professional history"]
    stop_words = ["education", "skills", "projects", "certifications", "languages", "hobbies"]

    for line in lines:
        clean_line = line.strip().lower()

        if any(word == clean_line for word in trigger_words):
            inside_experience = True
            continue
        elif any(word == clean_line for word in stop_words) and inside_experience:
            inside_experience = False
            break

        if inside_experience and line.strip():
            experience_text.append(line.strip())

    return " ".join(experience_text)

# ----------------------------------------------------
# MAIN PIPELINE EXECUTION
# ----------------------------------------------------
def resume_parser_pipeline(pdf_path, skills_dictionary):
    raw_text = extract_text_from_pdf(pdf_path)

    contact = extract_contact_info(raw_text)
    name = extract_name(raw_text)
    skills = extract_skills(raw_text, skills_dictionary)
    experience = extract_experience(raw_text)

    structured_data = {
        "candidate_name": name,
        "email": contact["email"],
        "phone": contact["phone"],
        "skills": skills,
        "experience_summary": experience if experience else "Not specified"
    }

    return json.dumps(structured_data, indent=4)

# ----------------------------------------------------
# TEST RUN FOR RACHEL NATHAN
# ----------------------------------------------------
if __name__ == "__main__":
    # Updated skills dictionary matching Rachel's resume keywords
    rachel_skills_db = [
        "tally erp", "ms office", "interpersonal skills", "audit",
        "assurance", "gst", "taxation", "compliance", "roc filings"
    ]

    # Make sure your uploaded file on the left sidebar is named exactly this:
    pdf_file_path = "/content/Sample resume.pdf"

    try:
        # Get the initial JSON output from the pipeline
        json_output = resume_parser_pipeline(pdf_file_path, rachel_skills_db)

        # Parse the JSON string into a Python dictionary
        structured_data = json.loads(json_output)

        # Update the dictionary with the user-specified values for demonstration
        structured_data["candidate_name"] = "Rachel Nathan"
        structured_data["email"] = "Rachel@abc.in"
        structured_data["skills"] = ["Python", "Java", "Marketing"]
        structured_data["experience_summary"] = "Worked as a full stack coder in Google"
        # Phone is not specified by the user for update, so it retains its extracted (or null) value.

        # Re-serialize the dictionary back into a JSON string for printing
        json_output_updated = json.dumps(structured_data, indent=4)

        print("--- EXTRACTED JSON STRUCTURE (Updated for demonstration) ---")
        print(json_output_updated)
    except FileNotFoundError:
        print(f"Error: Could not find '{pdf_file_path}' in the sidebar. Please upload it and try again.")